### ISSUE TITLE
Resource handlers support

### ISSUE THREAD

**Issue by j-barata** [hank-cp/sbp#15]
Hello,

I'm trying to setup a resource provider within a plugin (the resources shall be provided by the plugin itself), and tried the following code :

> @Configuration
> @EnableWebMvc
> public class ImageProvider implements WebMvcConfigurer {
>   @Override
>   public void addResourceHandlers(ResourceHandlerRegistry registry) {
>     registry.addResourceHandler("/icons/*").addResourceLocations("classpath:/icons/");
>   }
> }

But I only get a `404 Error`.

Is this kind of feature currently supported ?
Thanks

**Comment by hank-cp** [comment]
SBP supports resource loading. Please check out this [document](https://github.com/hank-cp/sbp/blob/master/docs/how_it_works.md) that explain how sbp load resources.


and here are related the test cases:
* https://github.com/hank-cp/sbp/blob/d14a98f0bc1f283270b00fcb57e1e28bd5e5422d/demo-app/src/test/java/demo/sbp/app/PluginIntegrationTest.java#L223
* https://github.com/hank-cp/sbp/blob/d14a98f0bc1f283270b00fcb57e1e28bd5e5422d/demo-app/src/test/java/demo/sbp/app/PluginIntegrationTest.java#L247

**Comment by j-barata** [comment]
Thanks for your answer.

The idea was to expose the resources from the application, through the standard `WebMvcConfigurer` interface.
But when I set the `@EnableWebMvc` annotation on the application class I get the following error :

> java.lang.ClassCastException: class org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping cannot be cast to class org.laxture.sbp.internal.PluginRequestMappingHandlerMapping (org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping and org.laxture.sbp.internal.PluginRequestMappingHandlerMapping are in unnamed module of loader 'app')

**Comment by hank-cp** [comment]
static resource handing is added. 

Please check out this test case for details:
* https://github.com/hank-cp/sbp/blob/31614cf79ce3c25ac06f5dfe118469894aa1fffb/demo-app/src/test/java/demo/sbp/app/PluginIntegrationTest.java#L454

this feature is available at v0.1.6 and SNAPSHOOT.

**Comment by j-barata** [comment]
Hi,
Thank you very much for this (very) quick enhancement !

I'm trying to download the new version from maven central but it doesn't seem to be published yet (I tried with `0.1.6` `v0.1.6` `-SNAPSHOT` `-SNAPSHOOT` but it doesn't know this version).

**Comment by hank-cp** [comment]
sorry, fotget to publish...should be available now.

**Comment by j-barata** [comment]
Thanks, I was able to download the new version.

When I tried the new feature, I got the following messages :

> Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'resourceHandlerRegistrationCustomizer': Unsatisfied dependency expressed through field 'resourceProperties'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.web.ResourceProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

> Field resourceProperties in org.springframework.boot.autoconfigure.web.servlet.PluginResourceHandlerRegistrationCustomizer required a bean of type 'org.springframework.boot.autoconfigure.web.ResourceProperties' that could not be found.


From what I've seen in your recent changes, I can't guess what I could have missed (I basically only added some new configurations in the `application.yml`).

I tried both `development` and `deployment` modes and the result is the same.

**Comment by hank-cp** [comment]
I should have explained this supports a little bit more...

Sbp supports resource handling based on Spring Boots' `WebMvcAutoConfiguration`. So you will need the almost same configurations as enabling resource handling as Spring Boots do, that will be:

```
spring:
  mvc:
    static-path-pattern: /public/**
  resources:
    add-mappings: true
    cache:
      period: 3600
```

full version here: https://github.com/hank-cp/sbp/blob/31614cf79ce3c25ac06f5dfe118469894aa1fffb/demo-app/src/main/resources/application.yml

**Comment by j-barata** [comment]
Hello,
I switched to version 0.1.7 and it works fine !

Thanks a lot for your support.

**Comment by j-barata** [comment]
Hello,
I switched to version 0.1.7 and it works fine !

Thanks a lot for your support.

**Comment by DobrolubovaJane** [comment]
Hi @j-barata ! I have the same problem when Spring Bootstrap try to createController

java.lang.ClassCastException: class org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping cannot be cast to class org.laxture.sbp.internal.PluginRequestMappingHandlerMapping

What should I do to fix it?

**Comment by j-barata** [comment]
Hi @DobrolubovaJane 

All you have to do is to switch to 0.1.7 version (or upper) and to set this configuration in your "application.yml" :

> spring:
>   mvc:
>     static-path-pattern: /public/**
>   resources:
>     add-mappings: true
>     cache:
>       period: 3600

You can also have a look at this sample project : https://github.com/j-barata/marketbasket-sbp-sample
