### ISSUE TITLE
@Autowired support

### ISSUE THREAD

**Issue by j-barata** [hank-cp/sbp#16]
Hello,

In my plugins I've defined some service classes that implement an interface (and also provided a bean allowing to instantiate the service classes).
In the application I try to autowire these interfaces but I only get :

>Field <> in <> Component required a bean of type '<>' that could not be found.
>The injection point has the following annotations:
> - @org.springframework.beans.factory.annotation.Autowired(required=true)

It seems that the beans providing these components have not been recognized... or maybe I've missed something.
I already successfully tested the plugin manager "getExtensions" way, but now I would like to use the autowired annotation.

Is it supported ?

Thanks

**Comment by j-barata** [comment]
Hi,

I think I got it.

The `autowired` is correctly resolved if :
- I set the `Extension` annotation on the plugin component
- I provide a `bean` on application side (using the plugin manager to retrieve the expected extension)

Sorry, for the noise.
I close this issue.

**Comment by hank-cp** [comment]
You are right, plz take the `BookService` as example
