### ISSUE TITLE
Plugins lifecycle issue

### ISSUE THREAD

**Issue by j-barata** [hank-cp/sbp#18]
Hello,

I've identified an issue with the management of the plugins lifecycle.

I have three plugins A, B and C. The plugins B and C depends on the plugin A.
Initially, the three plugins A, B and C are started. Then I do the following actions (actions order is important).

1. A is stopped -> B and C are also stopped (**OK**)
2. B is started -> A is also started and C is still stopped (**OK**)
3. C is started -> A, B and C are started (**OK**)
4. A is stopped -> B and C are still started (**NOK** : dependent plugins should never be started if one of its dependencies is stopped, unless it's an optional dependency)

*I'm not sure if it's a SBP issue or a PF4J issue (?).*
*This issue can be reprocuded easily, but an existing example already exists [here](https://github.com/j-barata/marketbasket-sbp-sample)*.

**Comment by hank-cp** [comment]
It should be a pf4j issue. I have raised a new issue https://github.com/pf4j/pf4j/issues/394.

**Comment by hank-cp** [comment]
BTW, nice project:)

**Comment by hank-cp** [comment]
fixed by https://github.com/pf4j/pf4j/issues/394
