### ISSUE TITLE
Can't start with java 8

### ISSUE THREAD

**Issue by DobrolubovaJane** [hank-cp/sbp#20]
Hello!

Could you help me?

Error appeared, when I create bean for pluginManager

Error:(88, 23) java: cannot access org.laxture.sbp.SpringBootPluginManager
  bad class file: /C:/m2/org/laxture/sbp-core/0.1.7/sbp-core-0.1.7.jar!/org/laxture/sbp/SpringBootPluginManager.class
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by hank-cp** [comment]
Emmm....the release binary of SBP in maven central repo is built in JDK11.

Is it possible for you to work with JDK11? It's 2020 now...

**Comment by DobrolubovaJane** [comment]
We have project with java8 ((
But we need to use controllers in our plugins. Maybe you can give me advice, how to add them to pf4j?

**Comment by hank-cp** [comment]
@DobrolubovaJane v0.1.8 is release to support JDK 8.

**Comment by DobrolubovaJane** [comment]
@hank-cp Thank you so much!!! I'll try)

**Comment by DobrolubovaJane** [comment]
@hank-cp it works! Could you please tell me, do we have an opportunity to override bean in main context with bean from plugin context?

**Comment by hank-cp** [comment]
Override beans in main context is not suggested. You might take a look at pf4j extension: https://pf4j.org/doc/extensions.html

**Comment by DobrolubovaJane** [comment]
Ok, thank you
