### ISSUE TITLE
Different classLoader is used with spring-dev-tools

### ISSUE THREAD

**Issue by dtrouillet** [hank-cp/sbp#23]
When I use spring-dev-tools my api interface is in a different class loader : RestartClassLoader managed by Spring Dev Tools.
With this library, my Plugin can't upcasted in my API Interface (ClassCastException) because the API Interface is in other class loader (RestartClassLoader).

For now I remove spring-dev-tools in my prject.

**Comment by hank-cp** [comment]
Both pf4j and Spring Dev Tools do the the works by gaining control of classloader. It would be very difficult make them work together.

We are using IDEA Intellj, which provides hot swap at JRE level. You might consider it as replacement of Spring Dev Tools.
