### ISSUE TITLE
auto-start-plugin property doesn't work

### ISSUE THREAD

**Issue by DobrolubovaJane** [hank-cp/sbp#25]
![image](https://user-images.githubusercontent.com/11889911/102647837-826c9580-4177-11eb-8d1d-3c6b0b5afff9.png)

 In properties  auto-start-plugin = false, but didn't set to pluginManager.
 
 Please add changes also to java8 version.

**Comment by hank-cp** [comment]
Fixed by #24, released by v0.1.9

**Comment by DobrolubovaJane** [comment]
Thank you!
