### ISSUE TITLE
Add third-party lib to plugin

### ISSUE THREAD

**Issue by DobrolubovaJane** [hank-cp/sbp#27]
1. How can we add third-party lib to plugin? For example

<dependency>
            <groupId>org.apache.xmlbeans</groupId>
            <artifactId>xmlbeans</artifactId>
            <version>3.1.0</version>
            <scope>runtime</scope>
        </dependency>

Now we can only add dependency to main application pom. 

2. How can we get values from plugin properties file application.yaml from jar?

**Comment by hank-cp** [comment]
you need extra extra gradle config to achive this.

This [example] https://github.com/hank-cp/sbp/blob/master/plugins/demo-plugin-library/build.gradle) demostrate how to include additional JPA libs to plugin project.

**Comment by DobrolubovaJane** [comment]
@hank-cp Thank you! And could you please release new version of sbp-core with my pull request changes.

**Comment by hank-cp** [comment]
v0.1.10 is released.

BTW, you could always use `:SNAPSHOT` version, which is mapped to latest master code.

**Comment by hank-cp** [comment]
@DobrolubovaJane does your issue sloved now? I am closing this issue.
