### ISSUE TITLE
How plugins can read application.properties outside plugin jar

### ISSUE THREAD

**Issue by duttarnab** [hank-cp/sbp#29]
Hi there,

Trying to read `plugin-name.properties` in plugin jar file using `PropertySource`.
```
@PropertySource(value = "file:${admin-ui.home}/config/plugin-name.properties")
```

But it shows the below message when the plugin is started.

`java -jar hans-admin-ui-api-standalone.jar --admin-ui.home=D:\Projects\java\hans-admin-ui-api`

**Logs**
```
2021-02-25 18:02:58.338  INFO 11584 --- [           main] o.s.c.a.ConfigurationClassParser         : Properties location [file:${admin-ui.home}/config/plugin-name.properties] not resolvable: Could not resolve placeholder 'admin-ui.home' in value "file:${admin-ui.home}/config/plugin-name.properties"
```

We have also used `admin-ui.home` placeholder in the parent project. It is working there.

**Comment by hank-cp** [comment]
Let's clearify your question first. Is `admin-ui.home` declare in your main app's `application.properties` and you want to use it in plugin?

If yes, you could use [spring.sbp.plugin-properties](https://github.com/hank-cp/sbp/blob/master/docs/configuration.md#springsbpplugin-properties) to pass configuration from app to plugin.
