### ISSUE TITLE
Plugin not loading when using Swagger in Application with below error

### ISSUE THREAD

**Issue by youngtalento** [hank-cp/sbp#31]
**Configuration :**  
import springfox.documentation.swagger2.annotations.EnableSwagger2;
@EnableSwagger2 in Configuration class

**Error**
Ambiguous mapping. Cannot map 'springfox.documentation.oas.web.OpenApiControllerWebMvc@64c5516e' method \nspringfox.documentation.oas.web.OpenApiControllerWebMvc#getDocumentation(String, HttpServletRequest)\nto {GET [/v3/api-docs], produces [application/json || application/hal+json]}: There is already 'openApiControllerWebMvc' bean method\nspringfox.documentation.oas.web.OpenApiControllerWebMvc#getDocumentation(String, HttpServletRequest) mapped.

**Comment by hank-cp** [comment]
Could you create a reproducible repo for this?

**Comment by youngtalento** [comment]
sure, here we go _[https://github.com/youngtalento/sbp](https://github.com/youngtalento/sbp)_ , please run **RestApplication** under **demo-rest-webservice** module and we can reproduce this issue.

**Comment by hank-cp** [comment]
Plugin's applicationContext will look for Spring Boot autoconfiguration in classpath, so you need to exclude swagger autoconfigurations.

```
    @Override
    protected SpringBootstrap createSpringBootstrap() {
        SpringBootstrap bootstrap = new SpringBootstrap(this, ServicePluginStarter.class) {
            @Override
            protected String[] getExcludeConfigurations() {
                List<String> excludes = new ArrayList<>(
                    Arrays.asList(super.getExcludeConfigurations()));
                excludes.add("springfox.boot.starter.autoconfigure.OpenApiAutoConfiguration");
                return excludes.toArray(new String[]{});
            }
        };
        return bootstrap;
    }
```
 
complete patch [here](https://gist.github.com/hank-cp/61a3fa06263dbc84829b963928e6c188)
