### ISSUE TITLE
ClassCastException: class org.laxture.sbp.spring.boot.SbpAutoConfiguration$1

### ISSUE THREAD

**Issue by rterzman** [hank-cp/sbp#33]
Caused by: java.lang.ClassCastException: class org.laxture.sbp.spring.boot.SbpAutoConfiguration$1 cannot be cast to class org.laxture.sbp.SpringBootPluginManager (org.laxture.sbp.spring.boot.SbpAutoConfiguration$1 is in unnamed module of loader 'app'; org.laxture.sbp.SpringBootPluginManager is in unnamed module of loader org.pf4j.PluginClassLoader @69d3cf7e)
	at org.laxture.sbp.SpringBootPlugin.getPluginManager(SpringBootPlugin.java:183) ~[sbp-core-0.1.13.jar:na]
	at org.laxture.sbp.SpringBootPlugin.getMainApplicationContext(SpringBootPlugin.java:187) ~[sbp-core-0.1.13.jar:na]
	at org.laxture.sbp.spring.boot.SpringBootstrap.<init>(SpringBootstrap.java:238) ~[sbp-core-0.1.13.jar:na]
	at com.plugin.dynamic.DynamicPlugin.createSpringBootstrap(DynamicPlugin.java:15) ~[na:na]
	at org.laxture.sbp.SpringBootPlugin.<init>(SpringBootPlugin.java:73) ~[sbp-core-0.1.13.jar:na]
	at com.plugin.dynamic.DynamicPlugin.<init>(DynamicPlugin.java:10) ~[na:na]
	... 25 common frames omitted
	

It happens when I am trying to load a plugin from the *.zip.

**application.yml:**
`spring.sbp:
  enabled: true
  runtimeMode: deployment
  customPluginLoader:  org.pf4j.DefaultPluginLoader
  classes-directories:
  - out/production/classes
  - out/production/resources`

**Comment by hank-cp** [comment]
Could you print the file structure in your zip? Looks like you packed some some core classes into the zip by mistake.

**Comment by rterzman** [comment]
Here is a plugin zip structure: 

`Archive:  base-plugin.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  11-17-2021 18:16   classes/
        0  11-17-2021 18:16   classes/META-INF/
       61  11-17-2021 18:16   classes/META-INF/extensions.idx
        0  11-17-2021 18:16   classes/com/
        0  11-17-2021 18:16   classes/com/cahsir/
        0  11-17-2021 18:16   classes/com/cahsir/plugin/
        0  11-17-2021 18:16   classes/com/cahsir/plugin/base/
      671  11-17-2021 18:16   classes/com/cahsir/plugin/base/BasePluginStarter.class
      594  11-17-2021 18:16   classes/com/cahsir/plugin/base/BasePluginService.class
      881  11-17-2021 18:16   classes/com/cahsir/plugin/base/BasePlugin.class
       54  11-17-2021 18:16   classes/application.yaml
        0  11-17-2021 18:16   lib/
    30299  10-12-2021 21:58   lib/jsonassert-1.5.0.jar
     4771  11-12-2021 15:19   lib/spring-boot-starter-2.5.6.jar
   115638  10-12-2021 21:57   lib/jakarta.xml.bind-api-2.3.3.jar
  1950607  11-12-2021 15:19   lib/lombok-1.18.22.jar
     4797  11-12-2021 15:19   lib/spring-boot-starter-tomcat-2.5.6.jar
   666328  11-12-2021 15:19   lib/mockito-core-3.9.0.jar
   365536  11-12-2021 15:19   lib/jackson-core-2.12.5.jar
    17762  11-12-2021 15:19   lib/log4j-to-slf4j-2.14.1.jar
   288686  11-12-2021 15:19   lib/spring-expression-5.3.12.jar
    49414  11-12-2021 15:19   lib/objenesis-3.2.jar
   567349  11-12-2021 15:19   lib/junit-jupiter-params-5.7.2.jar
    26586  10-12-2021 21:58   lib/javax.annotation-api-1.3.2.jar
    41513  11-12-2021 15:19   lib/slf4j-api-1.7.32.jar
  1027845  11-12-2021 15:19   lib/spring-webmvc-5.3.12.jar
   231720  11-12-2021 15:19   lib/json-path-2.5.0.jar
    28385  11-17-2021 13:29   lib/sbp-core-0.1.5.jar
   679855  11-12-2021 15:41   lib/flyway-core-7.7.3.jar
     4793  11-12-2021 15:19   lib/spring-boot-starter-test-2.5.6.jar
   292027  11-12-2021 15:19   lib/logback-classic-1.2.6.jar
  3429957  11-12-2021 15:19   lib/tomcat-embed-core-9.0.54.jar
     2923  11-17-2021 13:19   lib/spring-static-ctx-0.1.2.jar
   300365  11-12-2021 15:19   lib/log4j-api-2.14.1.jar
   277416  11-12-2021 15:19   lib/tomcat-embed-websocket-9.0.54.jar
     4773  11-12-2021 15:41   lib/spring-boot-starter-aop-2.5.6.jar
   121790  11-08-2021 12:36   lib/asm-9.1.jar
   175588  11-12-2021 15:19   lib/junit-jupiter-api-5.7.2.jar
   182322  11-12-2021 15:19   lib/spring-boot-test-autoconfigure-2.5.6.jar
     4806  11-12-2021 15:19   lib/spring-boot-starter-web-2.5.6.jar
  4811399  11-12-2021 15:19   lib/assertj-core-3.19.0.jar
    20757  11-17-2021 13:29   lib/sbp-spring-boot-starter-0.1.5.jar
   118513  11-12-2021 15:41   lib/spring-boot-configuration-processor-2.5.6.jar
   255866  11-12-2021 15:19   lib/tomcat-embed-el-9.0.54.jar
  2087074  11-12-2021 15:41   lib/aspectjweaver-1.9.7.jar
   472431  11-12-2021 15:19   lib/logback-core-1.2.6.jar
    34438  11-12-2021 15:19   lib/jackson-datatype-jdk8-2.12.5.jar
   382809  11-12-2021 15:19   lib/spring-aop-5.3.12.jar
    46613  10-12-2021 21:57   lib/jakarta.activation-api-1.2.2.jar
   212870  11-12-2021 15:19   lib/junit-jupiter-engine-5.7.2.jar
     4589  11-12-2021 15:19   lib/jul-to-slf4j-1.7.32.jar
   326914  11-12-2021 15:19   lib/snakeyaml-1.28.jar
    24440  11-12-2021 15:19   lib/spring-jcl-5.3.12.jar
     2387  10-12-2021 21:58   lib/apiguardian-api-1.1.0.jar
    46843  11-11-2021 15:51   lib/java-semver-0.9.0.jar
   786641  11-12-2021 15:19   lib/spring-test-5.3.12.jar
   353793  10-12-2021 21:58   lib/commons-codec-1.15.jar
     6361  11-12-2021 15:19   lib/junit-jupiter-5.7.2.jar
   697204  11-12-2021 15:19   lib/spring-beans-5.3.12.jar
     4762  11-12-2021 15:19   lib/spring-boot-starter-logging-2.5.6.jar
     4747  11-12-2021 15:19   lib/spring-boot-starter-json-2.5.6.jar
     9440  11-12-2021 15:19   lib/jackson-module-parameter-names-2.12.5.jar
    25058  10-12-2021 21:57   lib/jakarta.annotation-api-1.3.5.jar
    29489  11-12-2021 15:19   lib/accessors-smart-2.4.7.jar
  1566280  11-12-2021 15:19   lib/spring-boot-autoconfigure-2.5.6.jar
   119227  11-12-2021 15:19   lib/json-smart-2.4.7.jar
   251219  11-12-2021 15:19   lib/byte-buddy-agent-1.10.22.jar
   219623  11-12-2021 15:19   lib/spring-boot-test-2.5.6.jar
  3510658  11-12-2021 15:19   lib/byte-buddy-1.10.22.jar
  1268455  11-12-2021 15:19   lib/spring-context-5.3.12.jar
    75704  11-12-2021 15:19   lib/jackson-annotations-2.12.5.jar
   181408  11-12-2021 15:19   lib/junit-platform-engine-1.7.2.jar
  1515991  11-12-2021 15:19   lib/jackson-databind-2.12.5.jar
     5428  10-12-2021 22:04   lib/mockito-junit-jupiter-3.9.0.jar
   186902  11-12-2021 15:41   lib/spring-context-support-5.3.12.jar
  1392985  11-12-2021 15:19   lib/spring-boot-2.5.6.jar
   587402  11-12-2021 15:41   lib/commons-lang3-3.12.0.jar
   123360  10-12-2021 21:58   lib/hamcrest-2.2.jar
   100008  11-12-2021 15:19   lib/junit-platform-commons-1.7.2.jar
  1633810  11-12-2021 15:19   lib/spring-web-5.3.12.jar
     7653  10-12-2021 21:58   lib/opentest4j-1.2.0.jar
   116557  11-16-2021 17:15   lib/pf4j-3.1.0.jar
    18279  10-12-2021 21:58   lib/android-json-0.0.20131108.vaadin1.jar
   120362  11-12-2021 15:19   lib/jackson-datatype-jsr310-2.12.5.jar
   168861  11-12-2021 15:19   lib/xmlunit-core-2.8.3.jar
  1480024  11-12-2021 15:19   lib/spring-core-5.3.12.jar
      143  11-17-2021 17:28   plugin.properties
---------                     -------
 36311889                     87 files
`

Also I ve added implementation into the github: https://github.com/rterzman/sbp-plugin


I found out interesting flow, if I use starter version of 1.5 it works as expected except one case: Beans from the plugin are not registered in the main application context. I can get bean from the PluginManager by common interface.

**Comment by hank-cp** [comment]
My guess is correct. You didn't build the zip file correctly. Please refer to this [doc](https://github.com/hank-cp/sbp/blob/master/docs/deployment.md) about how to build a plugin jar/zip. The provided example is written in Gradle, I have not used Maven for years, so you will have to write a Maven version by yourself. If you manage to work out a Maven version, please kindly consider contribute to our docs :P

**Comment by hank-cp** [comment]
Sorry I don't get the version _1.5_, of what? Which lib are you referring here?

> I found out interesting flow, if I use starter version of 1.5 it works as expected except one case: Beans from the plugin are not registered in the main application context. I can get bean from the PluginManager by common interface.

> if I use starter version higher then 1.5 I get that exception.

**Comment by rterzman** [comment]
I use the sbp-springboot-starter with a version 1.5

`    <dependency>
      <groupId>org.laxture</groupId>
      <artifactId>sbp-spring-boot-starter</artifactId>
      <version>0.1.5</version>
    </dependency>`
    
    And It works correctly. If I change version higher than  <version>0.1.5</version> it will throw an exception which I mentioned above.

**Comment by hank-cp** [comment]
Since `v0.1.6`, alone with supported static file resouce serving, class loading strategy is also optimized to for the sake of performance. Please always prefer newer version then older :)
