### ISSUE TITLE
Bean with that name has already been defined

### ISSUE THREAD

**Issue by paulsen-it** [hank-cp/sbp#36]
Hello,

I get the follow error message:

```
The bean 'resourceHandlerRegistrationCustomizer', defined in class path resource [org/laxture/sbp/spring/boot/SbpMvcPatchAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$ResourceChainCustomizerConfiguration.class] and overriding is disabled.
Action:
Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

The Action is not a Solution. Than I get another error message.

I use Spring Boot Version 2.6.8 and sbp-spring-boot-starter Version 0.1.13

Can you help me?

**Comment by hank-cp** [comment]
Could you create a reproducible repo for this issue?

**Comment by paulsen-it** [comment]
Here is a "empty" Project. The error message comes on compile with

mvn clean package spring-boot:repackage spring-boot:run

https://github.com/paulsen-it/SBP-Error

**Comment by hank-cp** [comment]
Please see the issue #34, sbp does not support Spring Boot 2.6.8 at the moment. 

You could check out branch `sprint-boot-2.6` and build a local release to to local repository as a workaround solution.

**Comment by hank-cp** [comment]
Spring Boot 2.6.x has been supported from [release#14](https://github.com/hank-cp/sbp/releases/tag/14)
