### ISSUE TITLE
How to get DataSource

### ISSUE THREAD

**Issue by syifarahmat** [hank-cp/sbp#4]
How to get DataSource in main App from plugin ??
Or Plugin datasource withaut set on plugin(application.yaml)

**Comment by syifarahmat** [comment]
I got it this way, maybe you can give a simpler example ...
In my Plugin Class :
![image](https://user-images.githubusercontent.com/11779955/80866111-2ff96a00-8cb7-11ea-9c7a-f6b3a3d17c45.png)

In my Componen :
![image](https://user-images.githubusercontent.com/11779955/80866131-5c14eb00-8cb7-11ea-8da7-e1464affb026.png)

Then result :
![image](https://user-images.githubusercontent.com/11779955/80866163-81095e00-8cb7-11ea-9ce2-5ea9f7b1fc91.png)


Thanks... 👍

**Comment by hank-cp** [comment]
This doc may help: https://github.com/hank-cp/sbp/blob/master/docs/persistence.md
