### ISSUE TITLE
Unit tetss for core, etc

### ISSUE THREAD

**Issue by christopinka** [hank-cp/sbp#40]
Not seeing unit tests for core, plugin, etc classes. Looks like there is recent work for sb 3.0. Looks good. Thanks

**Comment by hank-cp** [comment]
Unit test is mostly done by demo projects.

**Comment by hank-cp** [comment]
Supporting Spring Boot 3.0 is quite big challenge. A lot of depnedent libs have been changed. I still don't have a good plan to get it done.

**Comment by hank-cp** [comment]
Spring Boot 3 is supported by version `3.0-SNAPSHOT` now.
