### ISSUE TITLE
插件如何携带统一路径前缀

### ISSUE THREAD

**Issue by shaohuzhang1** [hank-cp/sbp#45]
例如 我插件plugins-a  我想他的所有接口都是以/plugins-a开头 但是我并不想在每个controller里面都写/plugins-a/xxx/xxx

**Comment by hank-cp** [comment]
理论上讲应该是可以, 但是会涉及到比较多对Spring Mvc/Flux底层的扩展和改动. 目前没有计划实现这个特性. 欢迎提交PR🙂
