### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Gracemansam** [hank-cp/sbp#51]
Thank you for your response, I have been able to start the plugin and have access to the endpoint inside the plugin. but pls can you explain how I can stop and update the plugin. And connect each plugin to the data base of the core. It was not that written in the Read Me file. Thank you.

**Comment by hank-cp** [comment]
Hi, you could find all significant usages in test cases right now. 

Sorry for the poor documentation, I am really running out of energy at the moment.

**Comment by hank-cp** [comment]
Hi @Gracemansam, you look like going into panic, posting your problem everywhere, even those issues are very possibly NOT relevent to your problem. It doesn't help you to solve your problem at all.

Why don't you create a demo repository like other programming guys, which could 100% reproduce the problem you are encountering, and describe your expecting result precisely, to help us to understand your problem quickly and easily. 

We are not super man with X-Ray eyes, could fix everything by just one glance.

**Comment by Gracemansam** [comment]
Okay, Apology for that. Thank you.
Currently, I have  fix all the issues execpt for the database.

**Comment by Gracemansam** [comment]
Thank you Hank for this wonderful framework. Attached below is my repo for both the demo core and the plugin. The data is not persisting in the database. I even use custom query but not working. Pls what am I doing work. https://github.com/Gracemansam/workingSbpCore.git ==.> core
https://github.com/Gracemansam/demoHiv.git ==>demoPlugin. 

Thank you.

**Comment by hank-cp** [comment]
You didn't config the project depedencies correcly. Please refer to this [demo project](https://github.com/hank-cp/sbp/tree/master/demo-jpa), and [JPA integration document](https://github.com/hank-cp/sbp/blob/master/docs/extensible_integration.md#jpahibernate)

Quick hint: You need to use `org.laxture:sbp-spring-boot-jpa-starter:3.2.24` and introduce `SbpJpaConfigurer` in the plugin.

**Comment by hank-cp** [comment]
Check your [ddl-auto](https://docs.spring.io/spring-boot/docs/1.1.0.M1/reference/html/howto-database-initialization.html#howto-initialize-a-database-using-jpa) configuration.

**Comment by Gracemansam** [comment]
ooops! Sorry, I forget to check that. Thank you hank for your constant response.

Pls one more thing, I implemented the security as you directed in the demo but I am still getting 401 even in unprotected endpoint. Any help pls. Thank you.
![save5](https://github.com/hank-cp/sbp/assets/42440376/87277ff0-e9a8-4b72-ba65-ba86e97f7c2f)
![save4](https://github.com/hank-cp/sbp/assets/42440376/b38996ed-1e98-48ed-a0f8-c492b51e5fe5)
![save3](https://github.com/hank-cp/sbp/assets/42440376/97683666-f83e-4f8f-8f73-2b545a3d94e5)
![save2](https://github.com/hank-cp/sbp/assets/42440376/d44fde82-53fe-4fa9-9acd-b9ff9edd6f68)
![save1](https://github.com/hank-cp/sbp/assets/42440376/ed01eb69-7fae-4b2d-addc-4e1a5c9f1b10)

**Comment by hank-cp** [comment]
Again, can your demo repo reproduce the 401 problem?

**Comment by Gracemansam** [comment]
Hello hank, Thank you for the constant support with the framework. I tried dockerizing the my application with the sbp. it complain of pf4j vulnerability. can you increase to version 3.11 of pf4j maybe the vulnerability has been fixed.
Below are the error message. You can help look into it. Thank you

An issue in pf4j pf4j v.3.9.0 and before allows a remote attacker to obtain sensitive information and execute arbitrary code via the expandIfZip method in the extract function.

An issue in pf4j pf4j v.3.9.0 and before allows a remote attacker to obtain sensitive information and execute arbitrary code via the loadpluginPath parameter.

An issue in pf4j pf4j v.3.9.0 and before allows a remote attacker to obtain sensitive information and execute arbitrary code via the zippluginPath parameter.

**Comment by hank-cp** [comment]
Have upgrade pf4j to 3.11.1 on latest version of sbp.
