### ISSUE TITLE
[SUPPORT]咨询

### ISSUE THREAD

**Issue by ywjwjwj** [hank-cp/sbp#55]
**Describe the problem**
我在编写minecraft插件时，了解到插件化的架构。
我发现了您的仓库和该仓库 https://github.com/halo-dev/halo
都是使用pl4j构建插件化，我希望能够从sbp和halo-dev 2套模板中获得灵感。
对此，我的技术水平一般，对这块框架模板的阅读有些困难。
希望在您的角度得到对该框架的看法。

**Comment by hank-cp** [comment]
使用sbp的开发体验会更接近于原生的spring boot开发, 开发者可以从头规划适合于自己项目情况的扩展点, 不受任何限制, 甚至可以开发插件的插件, 比较适合于业务场景相对复杂灵活的项目. 它的前端插件化可以虽然通过模板引擎的插件来实现, 但对流行的SPA框架, 比如vue/react.js插件化, 需要额外实现和部署. 这部份目前没有涵盖在sbp的开源代码中.

相较而言, halo提供了很多开箱即用的封装功能, 但相对的插件扩展也只能在其框架提供的扩展点中去发挥, 扩展性有一点的限制. 但上手门槛比sbp低.

**Comment by ywjwjwj** [comment]
谢谢
