### ISSUE TITLE
How to load external jar as plugins?

### ISSUE THREAD

**Issue by AnthonyNTK** [hank-cp/sbp#7]
Is that possible to load a plugin from a external jar at runtime?
For example, to haveg an app with a REST API as below:
```java
@RequestMapping(value = "/installplugin", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
public void install(@RequestBody(required = true) MultipartFile file) {
        URLClassLoader child = new URLClassLoader(
                new URL[] {myJar.toURI().toURL()},
                this.getClass().getClassLoader()
        );
        Class<?> clazz = Class.forName("mypackage.MyClass", true, loader);

       // pesudo code
       pluginManager.load(clazz);
       pluginManager.start("plugin-id");
}
```

then mypackage.MyClass (as a plugin) is a RestController:
```java
@RestController
@RequestMapping("/message")
public class MyClass {

	@RequestMapping(value = "/return", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
	public Message testMethod() {
		return new Message("HIHIHIHI");
	}
}
```

User should be able to call new endpoint with `/message/return` after plugin being installed.

**Comment by hank-cp** [comment]
Sure, sbp is totally runtime. Take a look at [PluginManagerController](https://github.com/hank-cp/sbp/blob/master/sbp-spring-boot-starter/src/main/java/org/laxture/sbp/spring/boot/PluginManagerController.java) and [spring.sbp.controller.base-path] (https://github.com/hank-cp/sbp/blob/master/docs/configuration.md#springsbpcontrollerbase-path)

**Comment by hank-cp** [comment]
to build the jar file you need to follow some rules. I will update that part of doc recently.

**Comment by hank-cp** [comment]
@AnthonyNTK I have commit demonstration code of building plugin jar. Please checkout 9107e87 for more details. Also, you could read the [doc](https://github.com/hank-cp/sbp/blob/master/docs/deployment.md) that describes further more.

**Comment by dtrouillet** [comment]
@hank-cp Is SBP compatible with pf4j-update?

**Comment by hank-cp** [comment]
> @hank-cp Is SBP compatible with pf4j-update?

Should be worked. SBP underlying is still pf4j, with exact same plugin loading mecanism as pf4j. 

In our project, we don't use pf4j-update, but upload plugin jar file to deploeyment path on server and let user decide reload plugin or not via `PluginController`.

**Comment by dtrouillet** [comment]
Ok, thanks @hank-cp
