### ISSUE TITLE
Missing dependency on maven central repository

### ISSUE THREAD

**Issue by fabioformosa** [hank-cp/sbp#8]
```
Missing artifact com.github.hank-cp:spring-static-ctx:jar:0.1.1
```

It's a transitive dependency imported by `sbp-spring-boot-starter` and it's not in maven central repository.

**Comment by hank-cp** [comment]
Release. Thanks to figure it out...😛

**Comment by fabioformosa** [comment]
You've published it with groupId `org.laxture` but `cdb-core` looks for `com.github.hank-cp:spring-static-ctx`.

**Comment by hank-cp** [comment]
`com.github.hank-cp:spring-static-ctx` is avaiable from https://jitpack.io/.

Have unify libs location from maven central. Please check out version `SNAPSHOT` for now, or add following config to your build.gradle (if you are using gradle):
```
    repositories {
        ......
        maven { url "https://jitpack.io" }
    }
```
