### ISSUE TITLE
Wrong groupId for spring-static-ctx dependency

### ISSUE THREAD

**Issue by fabioformosa** [hank-cp/sbp#9]
You've published `spring-static-ctx` with groupId `org.laxture` but cdb-core looks for `com.github.hank-cp:spring-static-ctx`.

**Comment by hank-cp** [comment]
`com.github.hank-cp:spring-static-ctx` is avaiable from https://jitpack.io/.

Have unify libs location from maven central. Please check out version `SNAPSHOT` for now, or add following config to your build.gradle (if you are using gradle):
```
    repositories {
        ......
        maven { url "https://jitpack.io" }
    }
```

**Comment by fabioformosa** [comment]
Ok, thanks! I've added `jitpack` as repository. I'm using maven, so I've added into my pom.xml:
```
<repositories>
      <repository>
          <id>jitpack.io</id>
          <url>https://jitpack.io</url>
      </repository>
    </repositories>
```
